# Generated by Django 3.2 on 2022-01-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dinner_Wizard', '0002_alter_recipe_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipe_ingredients', to='Dinner_Wizard.Ingredient'),
        ),
    ]
