# Generated by Django 3.2 on 2022-01-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dinner_Wizard', '0003_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ingredienttemplate',
            options={'ordering': ['name']},
        ),
    ]
